site_name: Treeo
repo_name: cgarciae/treeo
repo_url: https://github.com/cgarciae/treeo
site_url: https://cgarciae.github.io/treeo
nav:
- Getting Started: index.md
- User Guide:
    User Guide: user-guide/intro.md
    Defining Fields: user-guide/defining-fields.md
    Field Kinds: user-guide/field-kinds.md
    Node policy: user-guide/node-policy.md
    Functional API:
      Filter: user-guide/api/filter.md
      Update: user-guide/api/update.md
      Map: user-guide/api/map.md
    "Sugar \U0001F36C": user-guide/sugar.md
    State Management: user-guide/state-management.md
    Opaque static fields: user-guide/opaque-static-fields.md
    Non-hashable static fields: user-guide/non-hashable-static-fields.md
    Field Metadata: user-guide/field-metadata.md
- API Reference:
    ArrayLike: api/ArrayLike.md
    FieldInfo: api/FieldInfo.md
    FieldMetadata: api/FieldMetadata.md
    Hashable: api/Hashable.md
    KindMixin: api/KindMixin.md
    MISSING: api/MISSING.md
    Missing: api/Missing.md
    NOTHING: api/NOTHING.md
    Nothing: api/Nothing.md
    Opaque: api/Opaque.md
    Tree: api/Tree.md
    TreeMeta: api/TreeMeta.md
    add_field_info: api/add_field_info.md
    apply: api/apply.md
    field: api/field.md
    filter: api/filter.md
    map: api/map.md
    node: api/node.md
    static: api/static.md
    update: api/update.md
extra:
  search:
    language: en
  social:
  - icon: octicons/mark-github-16
    link: https://github.com/cgarciae
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/cgarciae88
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/cgarciae
theme:
  name: material
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/infinity
    repo: octicons/mark-github-16
markdown_extensions:
- pymdownx.arithmatex
- admonition
- pymdownx.highlight
- pymdownx.superfences
- codehilite:
    guess_lang: false
    use_pygments: true
    noclasses: true
    pygments_style: default
plugins:
- search
- mkdocs-jupyter
- mkdocstrings
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
