name: On Merge Master
on:
  push:
    branches:
      - master
  pull_request:
  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Changelog Builder
        uses: mikepenz/release-changelog-builder-action@v2.9.0
        id: github_release
        fromTag: 0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Changelog
        run: |
          echo ${{steps.github_release.outputs.changelog}}