name: Publish Package
on:
  release:
    types: [published]
jobs:
  publish-docs:
    if: false
    name: Publish Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry 📖
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.4

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
      
      - name: Build Docs 🔨
        run: |
          cp README.md docs/index.md
          python scripts/update_docs.py
          mkdocs build
        
      - name: Deploy Page 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: site
        
  publish-package:
    if: false 
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry 📖
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.4

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
      
      - name: Publish to PyPI
        run: |
          poetry build
          poetry publish \
            --username ${{ secrets.PYPI_USERNAME }} \
            --password ${{ secrets.PYPI_PASSWORD }}
