# Checks that we can build and validate the Unittest
name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
  test:
    name: Run Tests
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.2.1
        with:
          version: 1.2.1

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run Tests
        run: poetry run pytest --cov=treeo --cov-report=term-missing --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v1

      - name: Test Examples
        run: poetry run bash scripts/test-examples.sh

  test-import:
    name: Test Import without Dev Dependencies
    if: ${{ !contains(github.event.pull_request.title, 'WIP') }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.2.1
        with:
          version: 1.2.1

      - name: Install Dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --without dev
          poetry run pip install jax jaxlib
        
      - name: Test Import Treex
        run: |
          poetry run python -c "import treeo"
