name: Create Release

on:
  push:

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup
        id: setup
        run: |
          # install python dependencies
          pip install typer==0.4.0

          # variables
          echo "::set-output name=RELEASE_VERSION::0.0.10"


      - name: Test Environment
        # env:
        #   GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          RELEASE_VERSION='${{ steps.setup.outputs.RELEASE_VERSION }}'

          # setup git
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git remote -v

          # switch to master
          git pull origin master
          git checkout master

          # update version
          python scripts/update_version.py $RELEASE_VERSION
          git commit -am "Update version to $RELEASE_VERSION"

          # create tag
          git fetch --tags
          git tag $RELEASE_VERSION

          # push to master
          git push
          git push --tags

        
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          toTag: ${{ steps.setup.outputs.RELEASE_VERSION }}
          fromTag: 0.0.9

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.setup.outputs.RELEASE_VERSION }}
          release_name: ${{ steps.setup.outputs.RELEASE_VERSION }}
          body: ${{ steps.github_release.outputs.changelog }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}